GeoSpots/GeoSpots/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('api.urls')),

]

#handler404 = 'core.views.page_not_found'
#handler500 = 'core.views.server_error'
#handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
#if settings.DEBUG:
#    import debug_toolbar
#
#    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

GeoSpots/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('api/posts', views.get_posts),
    path('api/posts/create', views.create_post),
    path('api/posts/<str:pk>', views.get_post),
    path('api/posts/<str:pk>/update', views.update_post),
    
]

GeoSpots/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('map', views.map_page, name='map'),
    path('favorites/<str:username>/', views.favorites, name='favorites'),
    path('weather', views.weather, name='weather'),
    path('create', views.post_create, name='create_post'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/settings', views.settings, name='settings'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', views.add_like, name='add_like'),
    path('posts/comment_like/<int:pk>',
         views.add_like_comment, name='add_like_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

GeoSpots/users/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(template_name='users/password_change_form.html'),
        name='password_change'),
    path(
        'password_reset/',
        auth_views.PasswordResetView.as_view(
            template_name='users/password_reset_form.html'),
        name='password_reset_form'),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path(
        'reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'),
        name='users/password_reset_confirm'),
    path(
        'reset/done/', auth_views.PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('contact/', views.Contact.as_view(), name='contact_us')
]

GeoSpots/users/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=100)
    body = models.TextField()
    is_answered = models.BooleanField(default=False)

GeoSpots/posts/forms.py
from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _
from django import forms

from .models import Comment, LatLon, Map, Post, Profile


class PostForm(forms.ModelForm):
    template_name = 'post_form.html'

    class Meta:
        model = Post
        fields = ('title', 'text', 'group', 'image', 'lat', 'lon')
        labels = {
            'title': 'Name',
            'text': _('Text'),
            'group': _('Category'),
            'Coor': 'К какому посту относится',
            'image': 'Photo',
            'lat': 'Latitude',
            'lon': 'Longitude',
        }
        widgets = {'image': forms.ClearableFileInput(attrs={'class': 'custom-file-input'})}


class ExampleForm(forms.ModelForm):
    title = forms.CharField(label='Title', max_length=100)
    text = forms.CharField(label='Text', widget=forms.Textarea)

    latitude = forms.DecimalField(label='Latitude', required=False)
    longitude = forms.DecimalField(label='Longitude', required=False)
    photo = forms.ImageField(label='Photo', required=False)

    def __init__(self, *args, **kwargs):
        super(ExampleForm, self).__init__(*args, **kwargs)
        self.fields['latitude'].widget = forms.HiddenInput()
        self.fields['longitude'].widget = forms.HiddenInput()
        self.fields['photo'].widget = forms.HiddenInput()

    def add_place(self):
        self.fields['latitude'].widget = forms.TextInput()
        self.fields['longitude'].widget = forms.TextInput()

    def add_photo(self):
        self.fields['photo'].widget = forms.ClearableFileInput()

class MapForm(ModelForm):
    class Meta:
        model = Map
        fields = ('destination',)
        labels = {
            'destination': 'destination',
        }


class LatLonForm(ModelForm):
    class Meta:
        model = LatLon
        fields = ('title', 'lat', 'lon')
        labels = {
            'title': 'Point name',
            'lat': 'Latitude',
            'lon': 'Longitude',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст',
        }


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ('avatar',)
        labels = {
            'avatar': 'ava',
        }

GeoSpots/posts/views.py
import logging

import folium

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, LatLonForm, PostForm, ExampleForm
from .models import Post, User, Comment, Follow

import urllib.request
import json

from rest_framework.decorators import api_view
from rest_framework.response import Response

from rest_framework import status

import os
from dotenv import load_dotenv

load_dotenv()
secret_token = os.getenv('TOKEN_WEATHER')


logging.basicConfig(level=logging.INFO)


def index(request):
    """ Main page """
    logging.info('index started')
    post_list = Post.objects.all().select_related('author')
    post_list_random = Post.objects.all().select_related('author').order_by('?')
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_list_random': post_list_random,
    }
    return render(request, 'posts/index.html', context)


def map_page(request):
    """ Map page """
    logging.info('map started')
    form = LatLonForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    map_folium = folium.Map(
        location=[61.171310, 28.766600],
        width=1420, height=855, zoom_start=4
    )
    point_list = Post.objects.all().values()

    map_folium.add_child(folium.LatLngPopup())
    """ add marks to map """
    for i in point_list:
        for_title = i.get('title')
        for_lat = i.get('lat')
        for_lon = i.get('lon')
        for_group = i.get('group_id')
        """ add group to mark """
        if for_group == 2:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title,
                icon=folium.Icon(
                    icon="glyphicon-tower", prefix='glyphicon', color='black')
                    ).add_to(map_folium)
        elif for_group == 3:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title, icon=folium.Icon(
                    icon="glyphicon-tree-conifer",
                    prefix='glyphicon', color='green')
                    ).add_to(map_folium)
        else:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title, icon=folium.Icon(
                    icon="glyphicon-tint",
                    prefix='glyphicon')
                    ).add_to(map_folium)
    map_folium = map_folium._repr_html_()

    context = {
        'form': form,
        'map_folium': map_folium,
    }

    return render(request, 'posts/map.html', context)


def favorites(request, username):
    logging.info('favorites started')
    user = get_object_or_404(User, username=username)
    post_list = user.likes.select_related('group')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    post_counter = paginator.count
    page_obj = paginator.get_page(page_number)
    context = {
        'username': user,
        'post_counter': post_counter,
        'page_obj': page_obj,
    }
    return render(request, 'posts/favorites.html', context)


def weather(request):
    logging.info('weather started')
    if request.method == 'POST':
        city = request.POST['city']

        source = urllib.request.urlopen(
            'http://api.openweathermap.org/data/2.5/weather?q=' +
            city +
            '&units=metric&appid=' + secret_token + '&=' + secret_token
            ).read()
        list_of_data = json.loads(source)

        data = {
            "country_code": str(list_of_data['sys']['country']),
            "coordinate": str(list_of_data['coord']['lon']) + ', '
            + str(list_of_data['coord']['lat']),

            "temp": str(list_of_data['main']['temp']) + ' °C',
            "pressure": str(list_of_data['main']['pressure']),
            "humidity": str(list_of_data['main']['humidity']),
            'main': str(list_of_data['weather'][0]['main']),
            'description': str(list_of_data['weather'][0]['description']),
            'icon': list_of_data['weather'][0]['icon'],
        }

    else:
        data = {}

    return render(request, "posts/weather.html", data)


def post_detail(request, post_id):
    logging.info('post_detail started')
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_lat = post.lat
    post_lon = post.lon
    post_title = post.text
    post_group = post.group.id
    map_folium = folium.Map(
        location=[post_lat, post_lon],
        width=800, height=500, zoom_start=8)
    if post_group == 2:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tower", prefix='glyphicon', color='black')
                ).add_to(map_folium)
    elif post_group == 3:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tree-conifer",
                prefix='glyphicon', color='green')
                ).add_to(map_folium)
    else:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tint", prefix='glyphicon')
                ).add_to(map_folium)
    map_folium = map_folium._repr_html_()
    author_posts_count = post.author.posts.count()
    data = urllib.request.urlopen('https://api.openweathermap.org/data/2.5/weather?lat=' + str(post_lat) + '&lon=' + str(post_lon) + '&appid=' + secret_token + '&=' + secret_token + '&units=metric').read()
    list_of_data = json.loads(data)
    context = {
        'post': post,
        'author_posts_count': author_posts_count,
        'map_folium': map_folium,
        'temp': str(list_of_data['main']['temp']) + ' °C',
        'icon': list_of_data['weather'][0]['icon'],
        'country_code': str(list_of_data['sys']['country']),
        'description': str(list_of_data['weather'][0]['description']),

    }
    return render(request, template, context)


@login_required
def post_create(request):
    logging.info('post create started')
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    map_folium = folium.Map(
        location=[61.171310, 28.766600],
        width=800, height=500, zoom_start=4)
    point_list = Post.objects.all().values()
    map_folium.add_child(folium.LatLngPopup())

    for i in point_list:
        post_title = i.get('title')
        post_lat = i.get('lat')
        post_lon = i.get('lon')
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title).add_to(map_folium)
    map_folium = map_folium._repr_html_()
    context = {'form': form}

    return render(request, 'posts/create_post.html', context)


def profile(request, username):
    logging.info('profile started')
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    post_counter = paginator.count
    page_obj = paginator.get_page(page_number)
    context = {
        'username': user,
        'post_counter': post_counter,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    logging.info('add comment started')
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def add_like(request, post_id):
    logging.info('add_like started')
    post = get_object_or_404(Post, id=post_id)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        logging.info('removed')
    else:
        post.likes.add(request.user)
        logging.info('added')
    return redirect('posts:post_detail', post_id=post_id)


def add_like_comment(request, pk):
    comment = get_object_or_404(Comment, id=pk)
    if comment.likes_comment.filter(id=request.user.id).exists():
        comment.likes_comment.remove(request.user)
    else:
        comment.likes_comment.add(request.user)
    return redirect('posts:index')


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user).all()
    context = {
        'post_list': post_list,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if request.user.username == username:
        return redirect('posts:profile', username)
    following = get_object_or_404(User, username=username)
    already_follows = Follow.objects.filter(
        user=request.user,
        author=following
    ).exists()
    if not already_follows:
        Follow.objects.create(user=request.user, author=following)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    follower = get_object_or_404(Follow, author=following, user=request.user)
    follower.delete()
    return redirect('posts:profile', username)



GeoSpots/users/views.py
from django.contrib.auth.forms import PasswordResetForm
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import CreateView
from django.views.generic.edit import CreateView
from django.db import models
from django.contrib.auth.models import User

from .forms import ContactForm, CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'


class Contact(CreateView):
    form_class = ContactForm
    template_name = 'users/contact.html'


@csrf_exempt
class PasswordReset(PasswordResetForm):
    form_class = PasswordResetForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/password_reset_form.html'


#class UserProfile(models.Model):
#    user = models.OneToOneField

GeoSpots/posts/templates/users/logged_out.html
{% extends 'posts/base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

GeoSpots/posts/templates/users/login.html
# templates/users/login.html

{% extends "posts/base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <!-- Тест на внимательность. Без переопределения шаблона этого адреса
            не существует. Нужно что-то делать, иначе все упадет -->
            <a href="{% url 'users:password_reset_form' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

GeoSpots/posts/templates/users/password_change_form.html
{% extends 'posts/base.html' %}
{% block content%}
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
{% endblock %}

GeoSpots/posts/templates/users/password_reset_form.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Изменение пароля</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">
                <form method="post" action="../users/password_change_form.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">
                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>
              </div> <!-- card body -->
            </div> <!-- card -->
          </div> <!-- col -->
        </div> <!-- row -->
      </div>
    </main>
	  <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>

GeoSpots/posts/templates/users/signup.html

{% extends "posts/base.html" %}
{% block title %}Sign up{% endblock %}
{% block content %}

  <div class="row justify-content-center">
    
    <div class="col-md-4 p-2">
      <div class="card">
        
        <div class="card-header">
            Sign up
        </div>
        <div class="card-body">
          {# Этот блок будет показан, если в форме есть ошибки #}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}

            <form method="post" action="{% url 'users:signup' %}">
              {% csrf_token %}
              {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
              {% endfor %}
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    Sign up
                </button>
              </div>
            </form>
          </div> <!-- card body -->
        </div> <!-- card -->
      </div> <!-- col -->
  </div> <!-- row -->
{% endblock %}