GeoSpots/GeoSpots/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('api.urls')),

]

#handler404 = 'core.views.page_not_found'
#handler500 = 'core.views.server_error'
#handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
#if settings.DEBUG:
#    import debug_toolbar
#
#    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

GeoSpots/api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('api/posts', views.get_posts),
    path('api/posts/create', views.create_post),
    path('api/posts/<str:pk>', views.get_post),
    path('api/posts/<str:pk>/update', views.update_post),
    
]

GeoSpots/posts/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('map', views.map_page, name='map'),
    path('favorites/<str:username>/', views.favorites, name='favorites'),
    path('weather', views.weather, name='weather'),
    path('create', views.post_create, name='create_post'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('profile/<str:username>/settings', views.settings, name='settings'),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/like/', views.add_like, name='add_like'),
    path('posts/comment_like/<int:pk>',
         views.add_like_comment, name='add_like_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

GeoSpots/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import math

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=40)
    description = models.TextField(null=True)

    class Meta:
        verbose_name = 'Заголовок группы'

    def __str__(self):
        return self.title


class LatLon(models.Model):
    title = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)

    lat = models.DecimalField(max_digits=10, decimal_places=8)
    lon = models.DecimalField(max_digits=10, decimal_places=8)

    def __str__(self):
        return self.title


class Post(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group, blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )
    lat = models.DecimalField(max_digits=10, decimal_places=8)
    lon = models.DecimalField(max_digits=10, decimal_places=8)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text


class Comment(models.Model):
    post = models.ForeignKey(
        Post, blank=True, null=True,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    likes_comment = models.ManyToManyField(User, related_name='comment_likes', blank=True)

    def whenpublished(self):
        now = timezone.now()
        diff = now - self.pub_date

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds = diff.seconds

            if seconds == 1:
                return str(seconds) + "second ago"
            else:
                return str(seconds) + " seconds ago"

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes = math.floor(diff.seconds/60)

            if minutes == 1:
                return str(minutes) + " minute ago"
            else:
                return str(minutes) + " minutes ago"

        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours = math.floor(diff.seconds/3600)

            if hours == 1:
                return str(hours) + " hour ago"

            else:
                return str(hours) + " hours ago"

            # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days = diff.days

            if days == 1:
                return str(days) + " day ago"

            else:
                return str(days) + " days ago"

        if diff.days >= 30 and diff.days < 365:
            months = math.floor(diff.days/30)
            if months == 1:
                return str(months) + " month ago"

            else:
                return str(months) + " months ago"

        if diff.days >= 365:
            years = math.floor(diff.days/365)

            if years == 1:
                return str(years) + " year ago"

            else:
                return str(years) + " years ago"

    def __str__(self):
        return self.text


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    def __str__(self):
        return str(self.user.username)


class Map(models.Model):
    location = models.CharField(max_length=200)
    destination = models.CharField(max_length=200)
    distance = models.DecimalField(max_digits=10, decimal_places=2)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(f' {self.distance} km')


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    date_of_birth = models.DateTimeField()
    avatar = models.ImageField(
        'Avatar',
        upload_to='avatars',
        blank=True
    )

    def __str__(self):
        return str(self.user)

GeoSpots/posts/views.py
import logging

import folium

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, LatLonForm, PostForm, ExampleForm
from .models import Post, User, Comment, Follow

import urllib.request
import json

from rest_framework.decorators import api_view
from rest_framework.response import Response

from rest_framework import status

import os
from dotenv import load_dotenv

load_dotenv()
secret_token = os.getenv('TOKEN_WEATHER')


logging.basicConfig(level=logging.INFO)


def index(request):
    """ Main page """
    logging.info('index started')
    post_list = Post.objects.all().select_related('author')
    post_list_random = Post.objects.all().select_related('author').order_by('?')
    paginator = Paginator(post_list, 5)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'post_list_random': post_list_random,
    }
    return render(request, 'posts/index.html', context)


def map_page(request):
    """ Map page """
    logging.info('map started')
    form = LatLonForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
    map_folium = folium.Map(
        location=[61.171310, 28.766600],
        width=1420, height=855, zoom_start=4
    )
    point_list = Post.objects.all().values()

    map_folium.add_child(folium.LatLngPopup())
    """ add marks to map """
    for i in point_list:
        for_title = i.get('title')
        for_lat = i.get('lat')
        for_lon = i.get('lon')
        for_group = i.get('group_id')
        """ add group to mark """
        if for_group == 2:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title,
                icon=folium.Icon(
                    icon="glyphicon-tower", prefix='glyphicon', color='black')
                    ).add_to(map_folium)
        elif for_group == 3:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title, icon=folium.Icon(
                    icon="glyphicon-tree-conifer",
                    prefix='glyphicon', color='green')
                    ).add_to(map_folium)
        else:
            folium.Marker(
                location=[for_lat, for_lon],
                popup=for_title, icon=folium.Icon(
                    icon="glyphicon-tint",
                    prefix='glyphicon')
                    ).add_to(map_folium)
    map_folium = map_folium._repr_html_()

    context = {
        'form': form,
        'map_folium': map_folium,
    }

    return render(request, 'posts/map.html', context)


def favorites(request, username):
    logging.info('favorites started')
    user = get_object_or_404(User, username=username)
    post_list = user.likes.select_related('group')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    post_counter = paginator.count
    page_obj = paginator.get_page(page_number)
    context = {
        'username': user,
        'post_counter': post_counter,
        'page_obj': page_obj,
    }
    return render(request, 'posts/favorites.html', context)


def weather(request):
    logging.info('weather started')
    if request.method == 'POST':
        city = request.POST['city']

        source = urllib.request.urlopen(
            'http://api.openweathermap.org/data/2.5/weather?q=' +
            city +
            '&units=metric&appid=' + secret_token + '&=' + secret_token
            ).read()
        list_of_data = json.loads(source)

        data = {
            "country_code": str(list_of_data['sys']['country']),
            "coordinate": str(list_of_data['coord']['lon']) + ', '
            + str(list_of_data['coord']['lat']),

            "temp": str(list_of_data['main']['temp']) + ' °C',
            "pressure": str(list_of_data['main']['pressure']),
            "humidity": str(list_of_data['main']['humidity']),
            'main': str(list_of_data['weather'][0]['main']),
            'description': str(list_of_data['weather'][0]['description']),
            'icon': list_of_data['weather'][0]['icon'],
        }

    else:
        data = {}

    return render(request, "posts/weather.html", data)


def post_detail(request, post_id):
    logging.info('post_detail started')
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, id=post_id)
    post_lat = post.lat
    post_lon = post.lon
    post_title = post.text
    post_group = post.group.id
    map_folium = folium.Map(
        location=[post_lat, post_lon],
        width=800, height=500, zoom_start=8)
    if post_group == 2:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tower", prefix='glyphicon', color='black')
                ).add_to(map_folium)
    elif post_group == 3:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tree-conifer",
                prefix='glyphicon', color='green')
                ).add_to(map_folium)
    else:
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title, icon=folium.Icon(
                icon="glyphicon-tint", prefix='glyphicon')
                ).add_to(map_folium)
    map_folium = map_folium._repr_html_()
    author_posts_count = post.author.posts.count()
    data = urllib.request.urlopen('https://api.openweathermap.org/data/2.5/weather?lat=' + str(post_lat) + '&lon=' + str(post_lon) + '&appid=' + secret_token + '&=' + secret_token + '&units=metric').read()
    list_of_data = json.loads(data)
    context = {
        'post': post,
        'author_posts_count': author_posts_count,
        'map_folium': map_folium,
        'temp': str(list_of_data['main']['temp']) + ' °C',
        'icon': list_of_data['weather'][0]['icon'],
        'country_code': str(list_of_data['sys']['country']),
        'description': str(list_of_data['weather'][0]['description']),

    }
    return render(request, template, context)


@login_required
def post_create(request):
    logging.info('post create started')
    form = PostForm(request.POST or None, files=request.FILES or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    map_folium = folium.Map(
        location=[61.171310, 28.766600],
        width=800, height=500, zoom_start=4)
    point_list = Post.objects.all().values()
    map_folium.add_child(folium.LatLngPopup())

    for i in point_list:
        post_title = i.get('title')
        post_lat = i.get('lat')
        post_lon = i.get('lon')
        folium.Marker(
            location=[post_lat, post_lon],
            popup=post_title).add_to(map_folium)
    map_folium = map_folium._repr_html_()
    context = {'form': form}

    return render(request, 'posts/create_post.html', context)


def profile(request, username):
    logging.info('profile started')
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all()
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    post_counter = paginator.count
    page_obj = paginator.get_page(page_number)
    context = {
        'username': user,
        'post_counter': post_counter,
        'page_obj': page_obj,
    }
    return render(request, 'posts/profile.html', context)


@login_required
def add_comment(request, post_id):
    logging.info('add comment started')
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


def add_like(request, post_id):
    logging.info('add_like started')
    post = get_object_or_404(Post, id=post_id)
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        logging.info('removed')
    else:
        post.likes.add(request.user)
        logging.info('added')
    return redirect('posts:post_detail', post_id=post_id)


def add_like_comment(request, pk):
    comment = get_object_or_404(Comment, id=pk)
    if comment.likes_comment.filter(id=request.user.id).exists():
        comment.likes_comment.remove(request.user)
    else:
        comment.likes_comment.add(request.user)
    return redirect('posts:index')


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user).all()
    context = {
        'post_list': post_list,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    if request.user.username == username:
        return redirect('posts:profile', username)
    following = get_object_or_404(User, username=username)
    already_follows = Follow.objects.filter(
        user=request.user,
        author=following
    ).exists()
    if not already_follows:
        Follow.objects.create(user=request.user, author=following)
    return redirect('posts:profile', username)


@login_required
def profile_unfollow(request, username):
    following = get_object_or_404(User, username=username)
    follower = get_object_or_404(Follow, author=following, user=request.user)
    follower.delete()
    return redirect('posts:profile', username)



GeoSpots/posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}
  <head> 
    <link rel="stylesheet" href="{% static 'css/style.css' %}">



    <title>
      {% block title %}
        GeoSpots app
      {% endblock %}
    </title>
    
  </head>
  <body>
    <header>
      {% include 'posts/includes/header.html' %}
    </header>
    
    <main>
      <center>
        {% block content %}
          {% include 'post_form.html' %}
        {% endblock %}
      </center>
    <footer class="border-top text-center py-3 bodycolor" >       
      {% include 'posts/includes/footer.html' %}
    </footer>
  </body>

GeoSpots/posts/templates/posts/create_post.html
{% extends 'posts/base.html'%}
{% block title %}
{% load thumbnail %}
{% if is_edit %}
  Редактировать пост
{% else %}
  Новый пост
{% endif %} 
{% endblock title %}
{% block content%}







<div class='padding_top'>
  <div class="container py-5">
    <form method="post" enctype="multipart/form-data" action="{% url 'posts:create_post' %}">
      {% csrf_token %}
      <div class="form-group">
        <label for="{{ field.id_for_label }}">Title
          {{ field.title }}
        </label>
        <input textarea class="form-control" >
      </div>
      <div class="form-group">
        <label for="{{ field.id_for_label }}"> Text
          {{ field.text }}
        </label>
        <input textarea class="form-control" rows="3">
      </div>
      <div class="form-group">Latitude
        <label for="{{ field.id_for_label }}">
          {{ field.lat }}
        </label>
        <input textarea class="form-control">
      </div>
      <div class="form-group">
        <label for="{{ field.id_for_label }}">Longitude
          {{ field.lon }}
          <input textarea class="form-control">
        </label>
      </div>
      <div class="form-group">
        <label for="{{ field.id_for_label }}"> Group
          {{ field.group }}
        </label>
        <input type="hidden">
      </div>
      <div class="form-group">
        <label for="{{ field.id_for_label }}">Image
          {{ field.image }}
          <input type="file" class="form-control">
        </label>
      </div>
      <button type="submit" class="btn btn-primary">Send</button>
    </form>
  </div>
</div>
{% endblock content%}

GeoSpots/posts/templates/posts/favorites.html
{% extends 'posts/base.html' %}
{% block title %}
Following page
{% endblock %}

{% block header %}
блок title
{% endblock %}

{% block content %}
{% load thumbnail %}
<div class="bodycolor">
    <div id="padding_top">
        <div class="container text-center">
            <div class="row">
              <div class="col-10">
                <div class="container">        
                  <article>

                    {% for post in page_obj %}
                    <p>
                      <div class="article">
                        <div id="left">
                          <p><strong><big>{{ post.title }}</big></strong> | {{ post.group.title }}  </p>
                          <p>{{ post.text|linebreaksbr }}</p>
                          <div style='border-radius: 5px;'>

                            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                              <img class="card-img my-2"  src="{{ im.url }}">
                            {% endthumbnail %}
                          </div>
                        {% if not forloop.last %}
                        {% endif %}
                        <p class="card-text"><small class="text-muted">Comments </small></p>
                        <a class="btn btn-small btn-primary" href="{% url 'posts:post_detail' post.pk %}">
                          Explore
                        </a>
                    
                        </div>
                      </div>
                    {% endfor %}
                  </article>
                </div>
              </div>
              <div class="col">
                {% for post in page_obj %}
                    <p>
                      <div class="article">
                        <div class="left">
                          <p><strong><big>{{ post.title }}</big></strong> | {{ post.group.title }}  </p>
                          <p>{{ post.text|truncatewords:20 }}</p>
                          <div style='border-radius: 5px;'>
                            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                              <img class="card-img my-2"  src="{{ im.url }}">
                            {% endthumbnail %}
                          </div>
                        {% if not forloop.last %}
                        {% endif %}
                        <p class="card-text"><small class="text-muted">Comments </small></p>
                        <a class="btn btn-small btn-primary" href="{% url 'posts:post_detail' post.pk %}">
                          Explore
                        </a>
                    
                        </div>
                      </div>
                    {% endfor %}
              </div>
            </div>
        </div>
    </div>
</div>       
{% endblock %}

GeoSpots/posts/templates/posts/map.html
{% extends 'posts/base.html' %}
{% block title %}
Map
{% endblock %}

{% block header %}



{% endblock %}

{% block content %}
<div class="bodycolor">
    <div class="col-lg-9">
    
        <div class="padding_top">
            {{ map_folium|safe }}
        </div>
    </div>
</div>


{% endblock content %}

GeoSpots/posts/templates/posts/my_page.html
{% extends 'posts/base.html' %}
{% block title %}
My page
{% endblock %}

{% block header %}



{% endblock %}

{% block content %}
<div class="col-md-6">
    <form action="" method="POST" autocomplete="off">
        {% csrf_token %}
        {{form}}
        <button type="submit" class="btn btn-primary">confirm</button>
    </form>

    {{ map_folium|safe }}
</div>

{% endblock content %}

GeoSpots/posts/templates/posts/post_detail.html
{% extends 'posts/base.html'%}
{% block title %}
  Post {{ post.title }}
{% endblock title %}
{% block content %}  
{% load thumbnail %} 

<div class="bodycolor">
  <div id="padding_top">
  <!-- <div class="row">
    <div class="col-md-5">      
      <strong><h4>Post #{{ post.pk }}</h4></strong>
      <aside class="col-12 col-md-7"> 

          <ul class="list-group list-group-flush"> 
            <li class="list-group-item">       
              Author: {{ post.author }}
           </li>
            <li class="list-group-item">
              Pub date: {{ post.pub_date|date:"d E Y" }}
            </li>
            <li class="list-group-item">  
              Point:   {{ post.title }}
            </li>
            <li class="list-group-item">
              Category: {{ post.group.title }}
            </li>
            <li class="list-group-item">
              lat:   {{ post.lat }}
              <p>lon:   {{ post.lon }}</p>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:add_like' post.pk %}"> 
                <img src="/media/icons/like.jpg" width="25", height="25">
              </a>
              Likes: {{ post.likes.count }}
            </li>
          </ul>

          <div class="col d-flex justify-content-center">
            <div class=" card text-white bg-dark mb-6">
              <div class=" card-body">
                <h4><span class="badge badge-primary">Country Code :</span> {{country_code}}</h4>

                <h4><span class="badge badge-primary">Temperature in Celsius :</span> {{temp}}</h4>

                <h4><span class="badge badge-primary">Forecast : </span>  <img
                    src="http://openweathermap.org/img/w/{{icon}}.png" alt="Image" style="width:70px"></h4>
                <h4><span class="badge badge-primary">Description : </span> {{description}}</h4>
              </div>
            </div>
          </div>

      </aside>
    </div> -->
    
      <article class="col-md-7" >
        <div class="article">
          <p><strong><h4>{{ post.title }}</h4></strong> </p>
          <div container>
            <div class="left">
              <div class="container">
                <div class="row">
                  <div class="col d-flex justify-content-center">
                    <div class="card text-dark bg-light mb-6">
                      <div class="card-body">
                        <div class="row">
                          <div class="col-md-4">
                            <big><span>Country :</span> <span class="text-black">{{ country_code }}</span></big>
                          </div>
                          <div class="col-md-4">
                            <big><span>Temperature :</span> <span class="text-black">{{ temp }}</span></big>
                          </div>
                          <div class="col-md-4">
                            <big><img src="http://openweathermap.org/img/w/{{ icon }}.png" alt="Image" style="width: 70px;"></big>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                            <big><span>Description : </span> <span class="text-black">{{ description }}</span></big>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              <!--<div class="text-black">
                <big><span class="text-black">Country Code :</span> {{country_code}}</big>
                <big><span class="text-black">Coordinates [X,Y] :</span> {{coordinate}}</big>
                <big><span class="text-black">Temperature in Celsius :</span> {{temp}}</big>
                <big><span class="text-black">Pressure :</span> {{pressure}}</big> 
                <big><span class="text-black">Humidity : </span> {{humidity}}</big>
                <big><span class="text-black">Forecast : </span> {{main}} <img
                    src="http://otext-blackmg/w/{{icon}}.png" alt="Image" style="width:70px"></big>
                  <big><span class="text-black">Description : </span> {{description}}</big>
              </div>-->
            </div>
          </div>
          <p></p>
          <p></p>
          <div class="left">
            <p>{{ post.text|linebreaksbr }}</p>
          </div>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ map_folium|safe }} </p>
          
          {% if user.is_authenticated and user == post.author %}
            <a href='/'> Edit post</a>
          {% endif %} 
                    {% if not post.comments.all %}
                      <p>No comments yet</p>
                      <p><a href={% url 'posts:add_comment' post.pk %}> Add first comment</a>
                    {% else %}
                      <h3><strong>Comments:</strong></h3>
                      {% for comment in post.comments.all %}
                         <div class="card mb-3">
                          <div class="row g-5">
                            <div class="col-md-2">
                              {% if comment.author.profile.avatar %}
                                {% thumbnail post.author.profile.avatar "50x50" crop="center" upscale=True as im %}
                                  <img class="rounded-circle" src="{{ im.url }}">
                                {% endthumbnail %}
                                <p>{{ comment.author.username }}</p>


                              {% else %}
                                <img src="/media/avatars/noava.jpg" width="50", height="50" class="rounded-circle">
                                <p>{{ comment.author.username }}</p>

                              {% endif %}
                            </div>


                            <div class="col-md-8">
                              <div class="card-body">
                              
                                <p class="card-text">{{ comment.text }}</p>
                                <li class="list-group-item">
                                  <a href="{% url 'posts:add_like_comment' comment.pk %}"> 
                                    <img src="/media/icons/like.jpg" width="25", height="25">
                                  </a>
                                  Likes: {{ comment.likes_comment.count }}
                                </li>
                                <p class="card-text"><small class="text-muted">posted {{ comment.whenpublished }}</small></p>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endfor %} 


                          <form method="post" action="{% url 'posts:add_comment' post.id %}">
                            <input type="hidden" name="csrfmiddlewaretoken" value="" placeholder="Username">      
                            <div class="form-group mb-2">
                              <textarea name="text" cols="40" rows="1" class="form-control" required id="id_text">
                              </textarea>
                            </div>
                            <button type="submit" class="btn btn-primary">Send</button>
                            {% csrf_token %}
                          </form>

                    {% endif %}
          </div>
        </div>
{% endblock content %}

GeoSpots/posts/templates/posts/post_form.html
<form method="post" action="{% url 'posts:create_post' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.title.id_for_label }}">Name</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="{{ form.text.id_for_label }}">Text</label>
        {{ form.text }}
    </div>
    <input type="submit" value="Create Post">
</form>